name: habi_track
description: "A Flutter app to track daily habits using Firebase Firestore."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Firebase 
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dropdown_button2: ^2.3.9
  flutter_hooks: ^0.21.3+1
  provider: ^6.1.2
  animated_list_plus: ^0.5.2
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
