// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux.');
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5K95kls15pl-GQhiBAgVYhW08ym8k2uA',
    appId: '1:176300134015:web:3353624c82891c0785394a',
    messagingSenderId: '176300134015',
    projectId: 'habitrack-5f7fd',
    authDomain: 'habitrack-5f7fd.firebaseapp.com',
    storageBucket: "habitrack-5f7fd.appspot.com",
    measurementId: 'G-N4J2GXXKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23nBHr_0zSxeVPQywssUa0v9CKC72-G0',
    appId: '1:176300134015:android:420aad81a91006e685394a',
    messagingSenderId: '176300134015',
    projectId: 'habitrack-5f7fd',
    storageBucket: 'habitrack-5f7fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5I5ATpgekxNx3qbkZP9xAsPs47myiV8',
    appId: '1:176300134015:ios:1234c4da5fac7d8c85394a',
    messagingSenderId: '176300134015',
    projectId: 'habitrack-5f7fd',
    storageBucket: 'habitrack-5f7fd.appspot.com',
    iosBundleId: 'com.example.habiTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5I5ATpgekxNx3qbkZP9xAsPs47myiV8',
    appId: '1:176300134015:ios:1234c4da5fac7d8c85394a',
    messagingSenderId: '176300134015',
    projectId: 'habitrack-5f7fd',
    storageBucket: 'habitrack-5f7fd.appspot.com',
    iosBundleId: 'com.example.habiTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5K95kls15pl-GQhiBAgVYhW08ym8k2uA',
    appId: '1:176300134015:web:713eb88b2b5e74ea85394a',
    messagingSenderId: '176300134015',
    projectId: 'habitrack-5f7fd',
    authDomain: 'habitrack-5f7fd.firebaseapp.com',
    storageBucket: "habitrack-5f7fd.appspot.com",
    measurementId: 'G-THXEQQJC5X',
  );
}